name: Pruebas y cobertura de sobrecargar.py

on:
  push:
    paths:
      - 'fuente/**'
  pull_request:
    paths:
      - 'fuente/**'

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.3-alpha - 3.13.3-beta'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install coverage

      - name: Ejecutar script de pruebas
        working-directory: fuente
        id: pruebas
        shell: pwsh
        run: |
            $ErrorActionPreference = "Stop"
            $output = powershell -ExecutionPolicy Bypass -File correr_pruebas.ps1 | Tee-Object -Variable fullOutput

            $fullOutput | Out-File pruebas_output.txt -Encoding utf8

            # Detectar estado final
            $tieneErrores  = $fullOutput -match 'FAILED\s+\((.*?errors=\d+)'
            $tieneFallos   = $fullOutput -match 'FAILED\s+\((.*?failures=\d+)'
            $todoOK        = $fullOutput -match '^\s*OK\s*$'

            $lineaSobrecargar = $fullOutput | Where-Object { $_ -match 'sobrecargar\\sobrecargar\.py' }
            if (-not $lineaSobrecargar) {
              echo "::error::No se encontró la línea de cobertura de sobrecargar.py"
              exit 1
            }

            $campos = $lineaSobrecargar -split '\s+'
            $porcentaje = $campos[-1].TrimEnd('%') -as [double]
            echo "::notice::Cobertura de sobrecargar.py = $porcentaje%"

            if ($tieneErrores -or $porcentaje -lt 50) {
              echo "::error::Cobertura < 50% o errores en las pruebas."
              exit 1
            }

            if ($tieneFallos -or ($porcentaje -ge 50 -and $porcentaje -lt 65)) {
              echo "::warning::Pruebas con fallos o cobertura entre 50% y 65%. Revisión manual requerida."
              exit 1
            }

            if (-not $todoOK) {
              echo "::error::No se detectó salida OK, posible error de parsing."
              exit 1
            }

            echo "✅ Pruebas OK y cobertura suficiente."
